<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Management App For Boats</title>

    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="min-h-screen w-screen bg-white-800 text-purple-400">
    <main class="flex items-center flex-col gap-4 max-w-96 mx-auto py-20">
        <h1 class="text-4xl font-bold mb-10">Privacy Policy</h1>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pretium fringilla sollicitudin. Vivamus tristique ex nec erat congue scelerisque. Integer bibendum facilisis tellus at ullamcorper. Ut tortor tellus, tempor ac iaculis id, ultricies convallis orci. Donec sed orci justo. Sed ac facilisis neque. Nam quis diam placerat, molestie risus sed, auctor mi. Nunc scelerisque gravida tortor nec venenatis. In hendrerit neque mattis, interdum orci id, scelerisque tortor. Praesent ut gravida lectus.</p>

        <p>Maecenas et varius metus, non mollis sem. Vivamus tempus fringilla eros eu semper. Donec ac dolor mollis, vestibulum turpis id, vulputate velit. Etiam eget ipsum blandit, fermentum urna eu, vehicula magna. Suspendisse fermentum lacus tempus, euismod magna ac, egestas ex. Nulla commodo, urna ut varius luctus, augue leo pretium orci, at elementum lectus augue at lectus. Curabitur auctor augue quis odio tincidunt rutrum. Nunc venenatis porttitor est ac posuere.</p>

        <p>Nunc id sagittis magna. Vivamus in neque id nisi egestas elementum nec eu dolor. Duis a interdum dui, ut maximus purus. Fusce sollicitudin, neque sed auctor vehicula, purus eros gravida sem, sit amet vulputate magna ante sit amet mauris. Sed id lacus finibus, gravida quam porta, elementum augue. Suspendisse at dui commodo, gravida nunc sit amet, blandit nulla. Cras pellentesque semper justo, et mattis diam molestie sit amet. Fusce fermentum, arcu volutpat condimentum egestas, felis erat blandit arcu, non laoreet orci nulla commodo ex. Nulla facilisis augue sem, a pretium leo dapibus eleifend. Pellentesque consectetur lacus non quam rhoncus condimentum. Morbi dignissim lobortis quam, eu rutrum sem vestibulum vitae. Sed vel lorem nibh. Fusce sapien nisl, vehicula accumsan metus a, imperdiet fringilla orci. Donec tincidunt mollis turpis ut aliquet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>

        <p>Donec vitae sapien scelerisque, mattis diam id, feugiat augue. Nulla facilisi. Nullam efficitur ut elit at iaculis. Fusce id nibh non lorem sollicitudin tristique. Duis luctus vulputate orci. Fusce laoreet gravida dolor at tempor. Maecenas dapibus, tellus vitae vehicula commodo, ex nulla blandit purus, a ornare ante arcu quis est. Quisque malesuada est at est accumsan porttitor eget vitae nulla. Nulla quis diam nec felis dapibus vulputate. Morbi a malesuada magna. Maecenas in tellus pulvinar, sagittis purus eu, vehicula tortor. Integer lobortis mi nibh, a tempus augue maximus quis. Sed vel lorem ligula. Nam quis nisi sed enim sagittis malesuada consectetur non turpis. Etiam eu hendrerit arcu.</p>

        <p>Donec in auctor tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut scelerisque sapien sed quam facilisis, ac tempus tortor porttitor. Duis id est eget nibh fringilla hendrerit nec ut nulla. Curabitur tincidunt sapien mauris. Donec porttitor, mi id tristique pretium, massa velit molestie dui, at fringilla nisi mauris vitae leo. Sed dapibus cursus posuere. Maecenas a dolor turpis. Sed imperdiet molestie ligula dignissim suscipit. Nam in urna nec neque cursus eleifend ac condimentum lacus.</p>

        <p>Donec nec lacus ac dui porta sagittis ac vitae sem. Vivamus ac fermentum mauris, at egestas ligula. Nulla facilisi. Mauris pretium diam nec neque egestas egestas. Ut tincidunt lorem non placerat fermentum. Aenean vitae efficitur mauris. Vestibulum euismod, mauris vel fermentum viverra, tellus sem finibus nibh, nec hendrerit felis mauris nec arcu.</p>

        <p>Ut sit amet varius orci. Maecenas vitae lacus et nibh lobortis pharetra. Etiam iaculis lorem sed fermentum iaculis. Duis ut enim vitae sem commodo mattis. Suspendisse maximus molestie molestie. Nulla a pulvinar orci. Praesent efficitur, purus eu viverra sagittis, odio turpis rhoncus nunc, sit amet placerat magna tellus sed velit. Proin sed consectetur nibh. Morbi vitae pretium nulla. In ac massa pharetra, hendrerit dui ac, vehicula sapien. Duis pretium id elit vel rutrum. Nunc nec lectus sollicitudin, elementum elit non, scelerisque ipsum. Nunc et neque vel purus vehicula elementum sit amet sed dolor. Ut placerat nisi suscipit eros placerat, ac consectetur dui ornare. Cras finibus scelerisque vehicula.</p>

        <p>Proin erat nisi, aliquam at felis ut, aliquet aliquet ligula. Quisque venenatis feugiat ipsum. Aliquam erat volutpat. Aliquam tincidunt nibh pretium nulla venenatis congue. Nullam vitae ipsum finibus, ultricies quam eu, sodales nulla. Aliquam et odio ut sem faucibus auctor a porta nisl. Donec pellentesque mauris nulla, nec rhoncus tortor ultrices vitae. Nam consequat finibus ornare. Fusce quis nulla lorem.</p>

        <p>Sed ac orci feugiat, ultrices nulla ac, luctus mauris. Donec pellentesque, diam quis consectetur semper, ipsum sem mattis arcu, at mattis risus justo ut sem. Curabitur a dapibus tortor. Proin vitae luctus purus, nec egestas turpis. Fusce sollicitudin, nibh quis vestibulum semper, dui sem viverra orci, eget viverra neque ipsum a urna. Vestibulum vel orci sed lorem finibus sodales in sed nisl. Donec condimentum ornare facilisis. Nunc fringilla nulla arcu.</p>

        <p>Etiam ullamcorper ex odio, non viverra urna fringilla sed. In elementum justo neque, et eleifend odio mattis at. In et rutrum elit. Sed commodo vestibulum neque, id pulvinar lectus vulputate ut. Etiam lacus risus, iaculis quis augue nec, venenatis pretium libero. Curabitur non mauris enim. Suspendisse porta diam sem, eget gravida orci cursus vitae.</p>

        <p>Pellentesque finibus, leo vitae gravida viverra, diam odio feugiat ex, at vulputate lacus ante id ex. Aliquam erat volutpat. Integer ullamcorper lorem sit amet magna elementum accumsan. Vivamus semper sit amet tortor vitae hendrerit. Phasellus eget tincidunt lorem. In vulputate sem eget tellus rutrum pulvinar. Curabitur sed nunc vestibulum orci varius blandit nec non velit. Nulla porttitor ipsum vel interdum pulvinar. Curabitur eu tristique enim, nec iaculis sem. Aenean id massa sit amet magna finibus varius. In a suscipit elit, non luctus tellus. Proin sollicitudin ligula sem, a congue massa consequat id. In accumsan accumsan consequat. Sed sagittis libero at leo auctor, quis vehicula sapien scelerisque. Nam bibendum porta nisl, at placerat metus molestie eu. Aenean vulputate vitae justo eu tempus.</p>

        <p>Sed elit lectus, feugiat ut pretium eget, pulvinar non tortor. Aliquam pulvinar felis arcu, non varius nisi hendrerit nec. Nunc in ex vulputate, dignissim magna vel, aliquam justo. Pellentesque eleifend sit amet velit nec mattis. Sed dignissim condimentum purus sed faucibus. Integer luctus erat a velit fermentum condimentum. Donec tortor neque, aliquam a nisi ac, lobortis faucibus magna. Aliquam fringilla cursus finibus. Nulla ut libero consequat, faucibus nulla eu, facilisis est. Vivamus ac euismod felis. Donec aliquam mauris consequat nisi dapibus, sodales faucibus odio tincidunt. In augue erat, feugiat sit amet arcu et, condimentum molestie odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec sed augue non orci tempus egestas at non arcu. Duis tincidunt bibendum est quis pellentesque. Pellentesque ornare, erat non blandit efficitur, nunc eros bibendum mauris, id malesuada metus ante in nibh.</p>

        <p>Donec pharetra sem in magna lobortis, sit amet aliquet urna facilisis. Morbi nulla ipsum, condimentum id quam et, elementum ullamcorper felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam faucibus libero a justo aliquam varius vitae sed est. Nam rhoncus luctus augue, a viverra quam fermentum ut. Vivamus interdum tempor porttitor. Integer at consequat dui, ut mollis elit. Morbi turpis felis, consectetur vitae maximus sit amet, vestibulum a est. Etiam tempus sagittis metus, id molestie magna. Vivamus aliquet lorem in convallis cursus. Mauris eu consectetur ante. Mauris efficitur tortor elit. Etiam dapibus luctus auctor. In ut dui quis enim sollicitudin auctor hendrerit et neque. In suscipit consectetur vehicula.</p>

        <p>Sed vitae augue orci. Duis massa lacus, lobortis porttitor nisl sit amet, vestibulum euismod massa. Aenean eros libero, venenatis ut ligula ac, posuere malesuada justo. Duis a ipsum in tortor ultrices dapibus. Nam aliquet, leo sit amet congue aliquam, nibh magna iaculis lorem, id placerat lectus lacus vitae justo. Donec malesuada auctor urna, at venenatis lorem posuere eu. Nulla ut fringilla est. Proin finibus feugiat metus nec tempus. Cras blandit lorem ligula. Integer efficitur leo eget arcu finibus, at cursus odio suscipit. Aliquam ac nunc nisi. Nam et pulvinar metus, ut sollicitudin massa.</p>

        <p>Etiam rutrum ex diam, in feugiat magna pharetra consectetur. Ut vestibulum ultricies libero, sit amet lobortis lorem mattis sit amet. Proin ultricies lorem nibh, non tempus nisl dignissim id. Fusce urna erat, pellentesque sed dolor quis, auctor suscipit sapien. Integer euismod elit at urna fermentum, eget imperdiet libero tempor. Vestibulum massa augue, finibus eget lectus at, dictum volutpat felis. Pellentesque cursus, enim eu pretium pretium, risus nisi tempus mauris, et eleifend libero dui ut lectus. Donec mattis urna nec augue tempor, sed iaculis tortor aliquam. Etiam luctus nulla vitae diam viverra vulputate. Pellentesque sagittis velit a felis cursus, accumsan placerat elit semper. Nullam et dolor porttitor, convallis dolor sed, efficitur enim. Vestibulum viverra, leo tincidunt lobortis sodales, sapien est efficitur diam, sit amet tincidunt nulla elit non risus. Cras finibus pharetra magna, vel tristique lorem fermentum sed. Nam commodo a ligula vestibulum volutpat. Praesent velit augue, sagittis eget efficitur a, egestas tempor dui. Integer lacinia, augue imperdiet tristique blandit, nunc justo blandit sapien, sed efficitur magna augue finibus neque.</p>

        <p>Mauris quis tempus mi, in eleifend augue. Quisque faucibus sodales nibh et tempor. In rutrum ut est sed mattis. Ut volutpat faucibus dui, et iaculis est euismod nec. Vestibulum facilisis mattis ante, ac bibendum risus tincidunt vel. Fusce vehicula sapien sapien. Fusce facilisis enim arcu, at facilisis nunc suscipit vel. Donec non consequat dui. Integer tempus metus non lorem vulputate porta. Cras id felis pharetra, convallis purus vel, pulvinar risus. Vivamus eget leo sed nunc viverra malesuada. Curabitur finibus imperdiet ante eget malesuada.</p>

        <p>Integer quis augue ac lectus condimentum pellentesque in sed nibh. Aliquam sagittis volutpat ex at iaculis. Pellentesque ac lacus ligula. Morbi congue vitae ipsum id aliquet. Quisque quis pretium metus. Pellentesque vitae nulla vitae urna semper dapibus eu in risus. Aenean volutpat lacus at efficitur egestas.</p>

        <p>Donec luctus diam eu ullamcorper rhoncus. Donec id velit tincidunt, dictum ante quis, lacinia ligula. Duis vehicula eros sed nulla hendrerit, et bibendum urna pulvinar. Nunc tincidunt tellus in vestibulum dapibus. Phasellus et sem non dui consectetur congue sed euismod urna. Mauris ut quam quis nibh fringilla aliquet non a eros. Sed in est rutrum, vehicula nulla sed, fermentum justo.</p>

        <p>Mauris semper justo id nibh consectetur auctor. Cras in justo sollicitudin, luctus sapien eget, egestas ante. Quisque viverra gravida ex, ullamcorper pellentesque dui vehicula quis. Suspendisse a nulla sit amet tellus accumsan iaculis. Proin elementum ligula imperdiet semper blandit. Suspendisse vitae lobortis nisi. Donec at odio massa. Proin laoreet sem ipsum, id porttitor massa consequat a. Etiam sem tortor, ultricies sit amet massa nec, dictum tincidunt libero. Nam turpis justo, ultricies nec ligula in, volutpat tincidunt enim. Maecenas facilisis rhoncus ornare.</p>

        <p>In leo diam, scelerisque ornare ultricies a, consequat id velit. Quisque feugiat quam vitae vestibulum tincidunt. Aenean elementum iaculis ex nec aliquam. Nunc et sodales libero. Nam nec metus molestie, consectetur ex eget, lobortis sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla facilisi. Sed tempus finibus justo, et imperdiet velit suscipit non. Nulla arcu arcu, hendrerit in nibh a, commodo consectetur sapien.</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse id tristique ante. Fusce vestibulum erat at vestibulum finibus. Mauris id viverra ex. Suspendisse vel felis quis ipsum lacinia aliquam ut in velit. Duis eleifend massa sit amet augue auctor, in aliquam velit ullamcorper. Donec rhoncus aliquam ultrices. Phasellus vitae cursus dolor. Sed commodo ex ut congue efficitur. Curabitur quis dolor a urna gravida maximus. Aliquam eget cursus sem. Suspendisse dolor dolor, fermentum id posuere non, elementum vitae lacus. Vestibulum sollicitudin elit id lacus viverra, at dignissim lorem pellentesque. Maecenas dictum nec eros iaculis ornare.</p>

        <p>Morbi tristique tincidunt metus, in imperdiet ex bibendum in. Morbi blandit at dui id fringilla. Pellentesque dictum dui eu nibh consectetur finibus. Duis at placerat orci. Vivamus maximus convallis justo, ut rutrum lorem fringilla in. Nulla viverra magna turpis, et dapibus ligula tincidunt sed. Maecenas porta sem sed enim interdum dignissim. Vivamus vitae suscipit risus, sed bibendum libero. Quisque quis feugiat ipsum. Morbi a nulla et magna fermentum sollicitudin eget vitae lorem.</p>

        <p>Praesent eget dignissim arcu. Ut in vehicula massa. Donec sed ullamcorper nisi. Curabitur in est gravida, dapibus felis in, maximus turpis. Nulla aliquam justo lacus, in hendrerit massa finibus ac. Nulla maximus bibendum feugiat. Nam fermentum odio sed malesuada consequat. Curabitur sit amet nulla a quam tempor condimentum. Etiam quis faucibus dolor. Nam congue turpis eu leo iaculis scelerisque. Phasellus ultricies diam sit amet nisl vehicula tempor.</p>

        <p>Donec vel lacus at neque vulputate molestie. Vivamus lacinia tortor purus, eget sollicitudin justo fringilla vitae. Etiam ex justo, rhoncus id fermentum eu, posuere quis odio. Nunc ac cursus diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean vestibulum augue sit amet dictum dictum. Morbi id pretium nibh, consequat eleifend tellus. Mauris laoreet semper felis, id vestibulum ipsum interdum eget. Quisque volutpat hendrerit est, sit amet pharetra erat malesuada in. Morbi ligula diam, convallis eget placerat in, vehicula a tellus. Phasellus et risus neque. Suspendisse varius aliquam pulvinar. Sed in turpis pretium, fermentum enim laoreet, condimentum libero. In cursus condimentum mi, ac hendrerit lorem euismod non. Ut interdum venenatis magna non tincidunt. Duis eu metus dolor.</p>

        <p>Aenean pellentesque enim quis sem ultricies, vel finibus justo sodales. Aenean ac justo non nibh hendrerit posuere. Nam euismod condimentum nulla a bibendum. Sed nec tincidunt ex. Proin ultrices semper massa volutpat condimentum. Duis cursus eros urna, vitae pretium mi consequat a. Fusce quis sodales est, et pellentesque felis. Praesent eget congue justo.</p>

        <a href="{{ route('welcome') }}" class="text-purple-400 hover:underline font-bold mt-10">Back to home</a>
    </main>
</body>

</html>
